/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ArbitSocketGUI */

#ifndef _Included_ArbitSocketGUI
#define _Included_ArbitSocketGUI
#ifdef __cplusplus
extern "C" {
#endif
#undef ArbitSocketGUI_FOCUS_TRAVERSABLE_UNKNOWN
#define ArbitSocketGUI_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef ArbitSocketGUI_FOCUS_TRAVERSABLE_DEFAULT
#define ArbitSocketGUI_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef ArbitSocketGUI_FOCUS_TRAVERSABLE_SET
#define ArbitSocketGUI_FOCUS_TRAVERSABLE_SET 2L
#undef ArbitSocketGUI_TOP_ALIGNMENT
#define ArbitSocketGUI_TOP_ALIGNMENT 0.0f
#undef ArbitSocketGUI_CENTER_ALIGNMENT
#define ArbitSocketGUI_CENTER_ALIGNMENT 0.5f
#undef ArbitSocketGUI_BOTTOM_ALIGNMENT
#define ArbitSocketGUI_BOTTOM_ALIGNMENT 1.0f
#undef ArbitSocketGUI_LEFT_ALIGNMENT
#define ArbitSocketGUI_LEFT_ALIGNMENT 0.0f
#undef ArbitSocketGUI_RIGHT_ALIGNMENT
#define ArbitSocketGUI_RIGHT_ALIGNMENT 1.0f
#undef ArbitSocketGUI_serialVersionUID
#define ArbitSocketGUI_serialVersionUID -7644114512714619750LL
#undef ArbitSocketGUI_serialVersionUID
#define ArbitSocketGUI_serialVersionUID 4613797578919906343LL
#undef ArbitSocketGUI_INCLUDE_SELF
#define ArbitSocketGUI_INCLUDE_SELF 1L
#undef ArbitSocketGUI_SEARCH_HEAVYWEIGHTS
#define ArbitSocketGUI_SEARCH_HEAVYWEIGHTS 1L
#undef ArbitSocketGUI_OPENED
#define ArbitSocketGUI_OPENED 1L
#undef ArbitSocketGUI_serialVersionUID
#define ArbitSocketGUI_serialVersionUID 4497834738069338734LL
#undef ArbitSocketGUI_DEFAULT_CURSOR
#define ArbitSocketGUI_DEFAULT_CURSOR 0L
#undef ArbitSocketGUI_CROSSHAIR_CURSOR
#define ArbitSocketGUI_CROSSHAIR_CURSOR 1L
#undef ArbitSocketGUI_TEXT_CURSOR
#define ArbitSocketGUI_TEXT_CURSOR 2L
#undef ArbitSocketGUI_WAIT_CURSOR
#define ArbitSocketGUI_WAIT_CURSOR 3L
#undef ArbitSocketGUI_SW_RESIZE_CURSOR
#define ArbitSocketGUI_SW_RESIZE_CURSOR 4L
#undef ArbitSocketGUI_SE_RESIZE_CURSOR
#define ArbitSocketGUI_SE_RESIZE_CURSOR 5L
#undef ArbitSocketGUI_NW_RESIZE_CURSOR
#define ArbitSocketGUI_NW_RESIZE_CURSOR 6L
#undef ArbitSocketGUI_NE_RESIZE_CURSOR
#define ArbitSocketGUI_NE_RESIZE_CURSOR 7L
#undef ArbitSocketGUI_N_RESIZE_CURSOR
#define ArbitSocketGUI_N_RESIZE_CURSOR 8L
#undef ArbitSocketGUI_S_RESIZE_CURSOR
#define ArbitSocketGUI_S_RESIZE_CURSOR 9L
#undef ArbitSocketGUI_W_RESIZE_CURSOR
#define ArbitSocketGUI_W_RESIZE_CURSOR 10L
#undef ArbitSocketGUI_E_RESIZE_CURSOR
#define ArbitSocketGUI_E_RESIZE_CURSOR 11L
#undef ArbitSocketGUI_HAND_CURSOR
#define ArbitSocketGUI_HAND_CURSOR 12L
#undef ArbitSocketGUI_MOVE_CURSOR
#define ArbitSocketGUI_MOVE_CURSOR 13L
#undef ArbitSocketGUI_NORMAL
#define ArbitSocketGUI_NORMAL 0L
#undef ArbitSocketGUI_ICONIFIED
#define ArbitSocketGUI_ICONIFIED 1L
#undef ArbitSocketGUI_MAXIMIZED_HORIZ
#define ArbitSocketGUI_MAXIMIZED_HORIZ 2L
#undef ArbitSocketGUI_MAXIMIZED_VERT
#define ArbitSocketGUI_MAXIMIZED_VERT 4L
#undef ArbitSocketGUI_MAXIMIZED_BOTH
#define ArbitSocketGUI_MAXIMIZED_BOTH 6L
#undef ArbitSocketGUI_serialVersionUID
#define ArbitSocketGUI_serialVersionUID 2673458971256075116LL
#undef ArbitSocketGUI_EXIT_ON_CLOSE
#define ArbitSocketGUI_EXIT_ON_CLOSE 3L
/*
 * Class:     ArbitSocketGUI
 * Method:    sendMessageToNetwork
 * Signature: (Ljava/lang/String;IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ArbitSocketGUI_sendMessageToNetwork
  (JNIEnv *, jobject, jstring, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
