/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CreateICMPHeader */

#ifndef _Included_CreateICMPHeader
#define _Included_CreateICMPHeader
#ifdef __cplusplus
extern "C" {
#endif
#undef CreateICMPHeader_FOCUS_TRAVERSABLE_UNKNOWN
#define CreateICMPHeader_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef CreateICMPHeader_FOCUS_TRAVERSABLE_DEFAULT
#define CreateICMPHeader_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef CreateICMPHeader_FOCUS_TRAVERSABLE_SET
#define CreateICMPHeader_FOCUS_TRAVERSABLE_SET 2L
#undef CreateICMPHeader_TOP_ALIGNMENT
#define CreateICMPHeader_TOP_ALIGNMENT 0.0f
#undef CreateICMPHeader_CENTER_ALIGNMENT
#define CreateICMPHeader_CENTER_ALIGNMENT 0.5f
#undef CreateICMPHeader_BOTTOM_ALIGNMENT
#define CreateICMPHeader_BOTTOM_ALIGNMENT 1.0f
#undef CreateICMPHeader_LEFT_ALIGNMENT
#define CreateICMPHeader_LEFT_ALIGNMENT 0.0f
#undef CreateICMPHeader_RIGHT_ALIGNMENT
#define CreateICMPHeader_RIGHT_ALIGNMENT 1.0f
#undef CreateICMPHeader_serialVersionUID
#define CreateICMPHeader_serialVersionUID -7644114512714619750LL
#undef CreateICMPHeader_serialVersionUID
#define CreateICMPHeader_serialVersionUID 4613797578919906343LL
#undef CreateICMPHeader_INCLUDE_SELF
#define CreateICMPHeader_INCLUDE_SELF 1L
#undef CreateICMPHeader_SEARCH_HEAVYWEIGHTS
#define CreateICMPHeader_SEARCH_HEAVYWEIGHTS 1L
#undef CreateICMPHeader_OPENED
#define CreateICMPHeader_OPENED 1L
#undef CreateICMPHeader_serialVersionUID
#define CreateICMPHeader_serialVersionUID 4497834738069338734LL
#undef CreateICMPHeader_DEFAULT_CURSOR
#define CreateICMPHeader_DEFAULT_CURSOR 0L
#undef CreateICMPHeader_CROSSHAIR_CURSOR
#define CreateICMPHeader_CROSSHAIR_CURSOR 1L
#undef CreateICMPHeader_TEXT_CURSOR
#define CreateICMPHeader_TEXT_CURSOR 2L
#undef CreateICMPHeader_WAIT_CURSOR
#define CreateICMPHeader_WAIT_CURSOR 3L
#undef CreateICMPHeader_SW_RESIZE_CURSOR
#define CreateICMPHeader_SW_RESIZE_CURSOR 4L
#undef CreateICMPHeader_SE_RESIZE_CURSOR
#define CreateICMPHeader_SE_RESIZE_CURSOR 5L
#undef CreateICMPHeader_NW_RESIZE_CURSOR
#define CreateICMPHeader_NW_RESIZE_CURSOR 6L
#undef CreateICMPHeader_NE_RESIZE_CURSOR
#define CreateICMPHeader_NE_RESIZE_CURSOR 7L
#undef CreateICMPHeader_N_RESIZE_CURSOR
#define CreateICMPHeader_N_RESIZE_CURSOR 8L
#undef CreateICMPHeader_S_RESIZE_CURSOR
#define CreateICMPHeader_S_RESIZE_CURSOR 9L
#undef CreateICMPHeader_W_RESIZE_CURSOR
#define CreateICMPHeader_W_RESIZE_CURSOR 10L
#undef CreateICMPHeader_E_RESIZE_CURSOR
#define CreateICMPHeader_E_RESIZE_CURSOR 11L
#undef CreateICMPHeader_HAND_CURSOR
#define CreateICMPHeader_HAND_CURSOR 12L
#undef CreateICMPHeader_MOVE_CURSOR
#define CreateICMPHeader_MOVE_CURSOR 13L
#undef CreateICMPHeader_NORMAL
#define CreateICMPHeader_NORMAL 0L
#undef CreateICMPHeader_ICONIFIED
#define CreateICMPHeader_ICONIFIED 1L
#undef CreateICMPHeader_MAXIMIZED_HORIZ
#define CreateICMPHeader_MAXIMIZED_HORIZ 2L
#undef CreateICMPHeader_MAXIMIZED_VERT
#define CreateICMPHeader_MAXIMIZED_VERT 4L
#undef CreateICMPHeader_MAXIMIZED_BOTH
#define CreateICMPHeader_MAXIMIZED_BOTH 6L
#undef CreateICMPHeader_serialVersionUID
#define CreateICMPHeader_serialVersionUID 2673458971256075116LL
#undef CreateICMPHeader_EXIT_ON_CLOSE
#define CreateICMPHeader_EXIT_ON_CLOSE 3L
/*
 * Class:     CreateICMPHeader
 * Method:    sendMessageToNetwork_ICMP
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIILjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIII)V
 */
JNIEXPORT void JNICALL Java_CreateICMPHeader_sendMessageToNetwork_1ICMP
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint, jint, jstring, jstring, jstring, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
