/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SendPacket */

#ifndef _Included_SendPacket
#define _Included_SendPacket
#ifdef __cplusplus
extern "C" {
#endif
#undef SendPacket_FOCUS_TRAVERSABLE_UNKNOWN
#define SendPacket_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef SendPacket_FOCUS_TRAVERSABLE_DEFAULT
#define SendPacket_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef SendPacket_FOCUS_TRAVERSABLE_SET
#define SendPacket_FOCUS_TRAVERSABLE_SET 2L
#undef SendPacket_TOP_ALIGNMENT
#define SendPacket_TOP_ALIGNMENT 0.0f
#undef SendPacket_CENTER_ALIGNMENT
#define SendPacket_CENTER_ALIGNMENT 0.5f
#undef SendPacket_BOTTOM_ALIGNMENT
#define SendPacket_BOTTOM_ALIGNMENT 1.0f
#undef SendPacket_LEFT_ALIGNMENT
#define SendPacket_LEFT_ALIGNMENT 0.0f
#undef SendPacket_RIGHT_ALIGNMENT
#define SendPacket_RIGHT_ALIGNMENT 1.0f
#undef SendPacket_serialVersionUID
#define SendPacket_serialVersionUID -7644114512714619750LL
#undef SendPacket_serialVersionUID
#define SendPacket_serialVersionUID 4613797578919906343LL
#undef SendPacket_INCLUDE_SELF
#define SendPacket_INCLUDE_SELF 1L
#undef SendPacket_SEARCH_HEAVYWEIGHTS
#define SendPacket_SEARCH_HEAVYWEIGHTS 1L
#undef SendPacket_OPENED
#define SendPacket_OPENED 1L
#undef SendPacket_serialVersionUID
#define SendPacket_serialVersionUID 4497834738069338734LL
#undef SendPacket_DEFAULT_CURSOR
#define SendPacket_DEFAULT_CURSOR 0L
#undef SendPacket_CROSSHAIR_CURSOR
#define SendPacket_CROSSHAIR_CURSOR 1L
#undef SendPacket_TEXT_CURSOR
#define SendPacket_TEXT_CURSOR 2L
#undef SendPacket_WAIT_CURSOR
#define SendPacket_WAIT_CURSOR 3L
#undef SendPacket_SW_RESIZE_CURSOR
#define SendPacket_SW_RESIZE_CURSOR 4L
#undef SendPacket_SE_RESIZE_CURSOR
#define SendPacket_SE_RESIZE_CURSOR 5L
#undef SendPacket_NW_RESIZE_CURSOR
#define SendPacket_NW_RESIZE_CURSOR 6L
#undef SendPacket_NE_RESIZE_CURSOR
#define SendPacket_NE_RESIZE_CURSOR 7L
#undef SendPacket_N_RESIZE_CURSOR
#define SendPacket_N_RESIZE_CURSOR 8L
#undef SendPacket_S_RESIZE_CURSOR
#define SendPacket_S_RESIZE_CURSOR 9L
#undef SendPacket_W_RESIZE_CURSOR
#define SendPacket_W_RESIZE_CURSOR 10L
#undef SendPacket_E_RESIZE_CURSOR
#define SendPacket_E_RESIZE_CURSOR 11L
#undef SendPacket_HAND_CURSOR
#define SendPacket_HAND_CURSOR 12L
#undef SendPacket_MOVE_CURSOR
#define SendPacket_MOVE_CURSOR 13L
#undef SendPacket_NORMAL
#define SendPacket_NORMAL 0L
#undef SendPacket_ICONIFIED
#define SendPacket_ICONIFIED 1L
#undef SendPacket_MAXIMIZED_HORIZ
#define SendPacket_MAXIMIZED_HORIZ 2L
#undef SendPacket_MAXIMIZED_VERT
#define SendPacket_MAXIMIZED_VERT 4L
#undef SendPacket_MAXIMIZED_BOTH
#define SendPacket_MAXIMIZED_BOTH 6L
#undef SendPacket_serialVersionUID
#define SendPacket_serialVersionUID 2673458971256075116LL
#undef SendPacket_EXIT_ON_CLOSE
#define SendPacket_EXIT_ON_CLOSE 3L
/*
 * Class:     SendPacket
 * Method:    sendMessageToNetwork_TCP
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIILjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIIIIIIIIIILjava/lang/String;IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_SendPacket_sendMessageToNetwork_1TCP
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint, jint, jstring, jstring, jstring, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jstring, jint, jint, jstring);

/*
 * Class:     SendPacket
 * Method:    sendMessageToNetwork_UDP
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIILjava/lang/String;Ljava/lang/String;Ljava/lang/String;IILjava/lang/String;IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_SendPacket_sendMessageToNetwork_1UDP
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint, jint, jstring, jstring, jstring, jint, jint, jstring, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
