/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SendIPPacket */

#ifndef _Included_SendIPPacket
#define _Included_SendIPPacket
#ifdef __cplusplus
extern "C" {
#endif
#undef SendIPPacket_FOCUS_TRAVERSABLE_UNKNOWN
#define SendIPPacket_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef SendIPPacket_FOCUS_TRAVERSABLE_DEFAULT
#define SendIPPacket_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef SendIPPacket_FOCUS_TRAVERSABLE_SET
#define SendIPPacket_FOCUS_TRAVERSABLE_SET 2L
#undef SendIPPacket_TOP_ALIGNMENT
#define SendIPPacket_TOP_ALIGNMENT 0.0f
#undef SendIPPacket_CENTER_ALIGNMENT
#define SendIPPacket_CENTER_ALIGNMENT 0.5f
#undef SendIPPacket_BOTTOM_ALIGNMENT
#define SendIPPacket_BOTTOM_ALIGNMENT 1.0f
#undef SendIPPacket_LEFT_ALIGNMENT
#define SendIPPacket_LEFT_ALIGNMENT 0.0f
#undef SendIPPacket_RIGHT_ALIGNMENT
#define SendIPPacket_RIGHT_ALIGNMENT 1.0f
#undef SendIPPacket_serialVersionUID
#define SendIPPacket_serialVersionUID -7644114512714619750LL
#undef SendIPPacket_serialVersionUID
#define SendIPPacket_serialVersionUID 4613797578919906343LL
#undef SendIPPacket_INCLUDE_SELF
#define SendIPPacket_INCLUDE_SELF 1L
#undef SendIPPacket_SEARCH_HEAVYWEIGHTS
#define SendIPPacket_SEARCH_HEAVYWEIGHTS 1L
#undef SendIPPacket_OPENED
#define SendIPPacket_OPENED 1L
#undef SendIPPacket_serialVersionUID
#define SendIPPacket_serialVersionUID 4497834738069338734LL
#undef SendIPPacket_DEFAULT_CURSOR
#define SendIPPacket_DEFAULT_CURSOR 0L
#undef SendIPPacket_CROSSHAIR_CURSOR
#define SendIPPacket_CROSSHAIR_CURSOR 1L
#undef SendIPPacket_TEXT_CURSOR
#define SendIPPacket_TEXT_CURSOR 2L
#undef SendIPPacket_WAIT_CURSOR
#define SendIPPacket_WAIT_CURSOR 3L
#undef SendIPPacket_SW_RESIZE_CURSOR
#define SendIPPacket_SW_RESIZE_CURSOR 4L
#undef SendIPPacket_SE_RESIZE_CURSOR
#define SendIPPacket_SE_RESIZE_CURSOR 5L
#undef SendIPPacket_NW_RESIZE_CURSOR
#define SendIPPacket_NW_RESIZE_CURSOR 6L
#undef SendIPPacket_NE_RESIZE_CURSOR
#define SendIPPacket_NE_RESIZE_CURSOR 7L
#undef SendIPPacket_N_RESIZE_CURSOR
#define SendIPPacket_N_RESIZE_CURSOR 8L
#undef SendIPPacket_S_RESIZE_CURSOR
#define SendIPPacket_S_RESIZE_CURSOR 9L
#undef SendIPPacket_W_RESIZE_CURSOR
#define SendIPPacket_W_RESIZE_CURSOR 10L
#undef SendIPPacket_E_RESIZE_CURSOR
#define SendIPPacket_E_RESIZE_CURSOR 11L
#undef SendIPPacket_HAND_CURSOR
#define SendIPPacket_HAND_CURSOR 12L
#undef SendIPPacket_MOVE_CURSOR
#define SendIPPacket_MOVE_CURSOR 13L
#undef SendIPPacket_NORMAL
#define SendIPPacket_NORMAL 0L
#undef SendIPPacket_ICONIFIED
#define SendIPPacket_ICONIFIED 1L
#undef SendIPPacket_MAXIMIZED_HORIZ
#define SendIPPacket_MAXIMIZED_HORIZ 2L
#undef SendIPPacket_MAXIMIZED_VERT
#define SendIPPacket_MAXIMIZED_VERT 4L
#undef SendIPPacket_MAXIMIZED_BOTH
#define SendIPPacket_MAXIMIZED_BOTH 6L
#undef SendIPPacket_serialVersionUID
#define SendIPPacket_serialVersionUID 2673458971256075116LL
#undef SendIPPacket_EXIT_ON_CLOSE
#define SendIPPacket_EXIT_ON_CLOSE 3L
/*
 * Class:     SendIPPacket
 * Method:    sendMessageToNetwork_IP
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_SendIPPacket_sendMessageToNetwork_1IP
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint, jint, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
