/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SendARPPacket */

#ifndef _Included_SendARPPacket
#define _Included_SendARPPacket
#ifdef __cplusplus
extern "C" {
#endif
#undef SendARPPacket_FOCUS_TRAVERSABLE_UNKNOWN
#define SendARPPacket_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef SendARPPacket_FOCUS_TRAVERSABLE_DEFAULT
#define SendARPPacket_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef SendARPPacket_FOCUS_TRAVERSABLE_SET
#define SendARPPacket_FOCUS_TRAVERSABLE_SET 2L
#undef SendARPPacket_TOP_ALIGNMENT
#define SendARPPacket_TOP_ALIGNMENT 0.0f
#undef SendARPPacket_CENTER_ALIGNMENT
#define SendARPPacket_CENTER_ALIGNMENT 0.5f
#undef SendARPPacket_BOTTOM_ALIGNMENT
#define SendARPPacket_BOTTOM_ALIGNMENT 1.0f
#undef SendARPPacket_LEFT_ALIGNMENT
#define SendARPPacket_LEFT_ALIGNMENT 0.0f
#undef SendARPPacket_RIGHT_ALIGNMENT
#define SendARPPacket_RIGHT_ALIGNMENT 1.0f
#undef SendARPPacket_serialVersionUID
#define SendARPPacket_serialVersionUID -7644114512714619750LL
#undef SendARPPacket_serialVersionUID
#define SendARPPacket_serialVersionUID 4613797578919906343LL
#undef SendARPPacket_INCLUDE_SELF
#define SendARPPacket_INCLUDE_SELF 1L
#undef SendARPPacket_SEARCH_HEAVYWEIGHTS
#define SendARPPacket_SEARCH_HEAVYWEIGHTS 1L
#undef SendARPPacket_OPENED
#define SendARPPacket_OPENED 1L
#undef SendARPPacket_serialVersionUID
#define SendARPPacket_serialVersionUID 4497834738069338734LL
#undef SendARPPacket_DEFAULT_CURSOR
#define SendARPPacket_DEFAULT_CURSOR 0L
#undef SendARPPacket_CROSSHAIR_CURSOR
#define SendARPPacket_CROSSHAIR_CURSOR 1L
#undef SendARPPacket_TEXT_CURSOR
#define SendARPPacket_TEXT_CURSOR 2L
#undef SendARPPacket_WAIT_CURSOR
#define SendARPPacket_WAIT_CURSOR 3L
#undef SendARPPacket_SW_RESIZE_CURSOR
#define SendARPPacket_SW_RESIZE_CURSOR 4L
#undef SendARPPacket_SE_RESIZE_CURSOR
#define SendARPPacket_SE_RESIZE_CURSOR 5L
#undef SendARPPacket_NW_RESIZE_CURSOR
#define SendARPPacket_NW_RESIZE_CURSOR 6L
#undef SendARPPacket_NE_RESIZE_CURSOR
#define SendARPPacket_NE_RESIZE_CURSOR 7L
#undef SendARPPacket_N_RESIZE_CURSOR
#define SendARPPacket_N_RESIZE_CURSOR 8L
#undef SendARPPacket_S_RESIZE_CURSOR
#define SendARPPacket_S_RESIZE_CURSOR 9L
#undef SendARPPacket_W_RESIZE_CURSOR
#define SendARPPacket_W_RESIZE_CURSOR 10L
#undef SendARPPacket_E_RESIZE_CURSOR
#define SendARPPacket_E_RESIZE_CURSOR 11L
#undef SendARPPacket_HAND_CURSOR
#define SendARPPacket_HAND_CURSOR 12L
#undef SendARPPacket_MOVE_CURSOR
#define SendARPPacket_MOVE_CURSOR 13L
#undef SendARPPacket_NORMAL
#define SendARPPacket_NORMAL 0L
#undef SendARPPacket_ICONIFIED
#define SendARPPacket_ICONIFIED 1L
#undef SendARPPacket_MAXIMIZED_HORIZ
#define SendARPPacket_MAXIMIZED_HORIZ 2L
#undef SendARPPacket_MAXIMIZED_VERT
#define SendARPPacket_MAXIMIZED_VERT 4L
#undef SendARPPacket_MAXIMIZED_BOTH
#define SendARPPacket_MAXIMIZED_BOTH 6L
#undef SendARPPacket_serialVersionUID
#define SendARPPacket_serialVersionUID 2673458971256075116LL
#undef SendARPPacket_EXIT_ON_CLOSE
#define SendARPPacket_EXIT_ON_CLOSE 3L
/*
 * Class:     SendARPPacket
 * Method:    sendMessageToNetwork_ARP
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_SendARPPacket_sendMessageToNetwork_1ARP
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
